//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatingEntities : DbContext
    {
        public DatingEntities()
            : base("name=DatingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eye_colors> eye_colors { get; set; }
        public virtual DbSet<genders> genders { get; set; }
        public virtual DbSet<hair_colors> hair_colors { get; set; }
        public virtual DbSet<hobbies> hobbies { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<profile_visits> profile_visits { get; set; }
        public virtual DbSet<user_categories> user_categories { get; set; }
        public virtual DbSet<user_details> user_details { get; set; }
        public virtual DbSet<user_hobbies> user_hobbies { get; set; }
        public virtual DbSet<user_hobbies_preferences> user_hobbies_preferences { get; set; }
        public virtual DbSet<user_images> user_images { get; set; }
        public virtual DbSet<user_preferences_age> user_preferences_age { get; set; }
        public virtual DbSet<user_preferences_eye_color> user_preferences_eye_color { get; set; }
        public virtual DbSet<user_preferences_gender> user_preferences_gender { get; set; }
        public virtual DbSet<user_preferences_hair_color> user_preferences_hair_color { get; set; }
        public virtual DbSet<user_preferences_height> user_preferences_height { get; set; }
        public virtual DbSet<user_preferences_hobbies> user_preferences_hobbies { get; set; }
        public virtual DbSet<user_preferences_weight> user_preferences_weight { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<ratings> ratings { get; set; }
    }
}
