//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_images
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string image_path { get; set; }
        public int profile_image { get; set; }
    }
}
