//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_details
    {
        public int user_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public int gender { get; set; }
        public int age { get; set; }
        public int height { get; set; }
        public int weight { get; set; }
        public string self_description { get; set; }
        public int eye_color { get; set; }
        public int hair_color { get; set; }
    }
}
