//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_preferences_eye_color
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int eye_color { get; set; }
    }
}
